#include<iostream>
using namespace std;
class Random
{
    public:
    int ran_num, guess_num;
    int  total_tries = 0;
    void guess(int,int);
};
void Random::guess(int guess_num,int ran_num)
{
     if (guess_num > ran_num)
			cout << "Too high!\n\n";
		else if (guess_num < ran_num)
			cout << "Too low!\n\n";
		else
			cout << "\nCorrect! You got it in " << total_tries << " guesses!\n";
        total_tries++;
}
int main()
{
    Random r;
	int ran_num, guess_num;
    int  total_tries = 0;
	ran_num = rand()%1000; 
	cout << "********************Try to guess the number generated by me********************\n\n";
    do
	{
		cout << "Enter a guess number (between 1 to 999) : ";
		cin >> guess_num;
		r.guess(guess_num,ran_num);
	} while (guess_num != ran_num);

	return 0;
}

